---
abstract: 'SQL DDL transformations and more'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Basename: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.6
  YAML: 0.39
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: http://fsf.org/licensing/licenses/gpl.html
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Translator
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  GD: 0
  Graph::Directed: 0
  GraphViz: 0
  IO::File: 0
  IO::Scalar: 0
  Spreadsheet::ParseExcel: 0.41
  Template: 2.1
  Text::ParseWords: 0
  Text::RecordParser: 0.02
  XML::LibXML: 1.61
  XML::Writer: 0.5
requires:
  Carp::Clan: 0
  Class::Accessor::Fast: 0
  Class::Base: 0
  Class::Data::Inheritable: 0.02
  Class::MakeMethods: 0
  DBI: 0
  Digest::SHA1: 2
  File::ShareDir: 1
  File::Spec: 0
  IO::Dir: 0
  Parse::RecDescent: 1.096
  Pod::Usage: 0
  perl: 5.005
resources:
  Ratings: http://cpanratings.perl.org/d/SQL-Translator
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SQL-Translator
  repository: https://sqlfairy.svn.sourceforge.net/svnroot/sqlfairy
version: 0.09005
