# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Translator
version:      0.03
version_from: lib/SQL/Translator.pm
installdirs:  site
requires:
    Class::Base:                   0.03
    File::Basename:                2.71
    File::Spec:                    0.85
    GD:                            2.07
    GraphViz:                      1.80
    IO::Dir:                       1.03
    IO::File:                      1.09
    IO::Scalar:                    2.10
    Parse::RecDescent:             1.94
    Pod::Usage:                    1.14
    Spreadsheet::ParseExcel:       0.26
    Template:                      2.10
    Test::Differences:             0.47
    Test::Exception:               0.15
    Test::More:                    0.47
    Text::ParseWords:              3.21
    Text::RecordParser:            0.04
    XML::Writer:                   0.40
    XML::XPath:                    1.13
    YAML:                          0.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
