---
abstract: 'SQL DDL transformations and more'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Differences: 0
  Test::Exception: 0.31
  Test::More: 0.88
  XML::Writer: 0.500
  YAML: 0.66
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Translator
no_index:
  directory:
    - inc
    - share
    - t
    - xt
recommends:
  GD: 0
  Graph::Directed: 0
  GraphViz: 0
  Spreadsheet::ParseExcel: 0.41
  Template: 2.20
  Text::RecordParser: 0.02
  XML::LibXML: 1.69
requires:
  Carp::Clan: 0
  DBI: 0
  Digest::SHA: 0
  File::ShareDir: 1.0
  List::MoreUtils: 0.09
  Moo: 1.000003
  Package::Variant: 1.001001
  Parse::RecDescent: 1.967009
  Sub::Quote: 0
  Try::Tiny: 0.04
  perl: 5.8.1
resources:
  Ratings: http://cpanratings.perl.org/d/SQL-Translator
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SQL-Translator
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/SQL-Translator.git
version: 0.11015
x_authority: cpan:JROBINSON
