# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Translator
version:      0.05
version_from: lib/SQL/Translator.pm
installdirs:  site
requires:
    Class::Base:                   0
    File::Basename:                0
    File::Spec:                    0
    GD:                            0
    GraphViz:                      0
    IO::Dir:                       0
    IO::File:                      0
    IO::Scalar:                    0
    Parse::RecDescent:             1.94
    Pod::Usage:                    0
    Spreadsheet::ParseExcel:       0
    Template:                      2.1
    Test::Differences:             0
    Test::Exception:               0
    Test::More:                    0
    Text::ParseWords:              0
    Text::RecordParser:            0.02
    XML::Writer:                   0
    XML::XPath:                    1.13
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
